---
output:
  data_folder: './data'
  log_folder: './data/logs'

stocks:
  data: 'example_data.csv'
  start: 360
  end: null
  metric: 'Adj Close'
  source: 'yahoo'
model:
  method: max_sharpe
  kpis:
    - rsi:
      - True
    - sma:
      - False
      - 12
      - 24
    - bbands:
      - True
      - 1   # std upper
      - 1   # std lower
      - 20  # sma
    - ema:
      - True
      - 12  # low
      - 26  # high
      - 50
bot:
  chat_id:
  token_id:

