---
output:
  data_folder: './data'
  log_folder: './data/logs'

stocks:
  data: 'example_data.csv'
  start: 360
  end: null
  metric: 'Adj Close'
  source: 'yahoo'
model:
  method: max_sharpe
  kpis:
    - rsi:
      - True
    - sma:
      - False
      - 12
      - 24
    - bbands:
      - True
      - 1   # std upper
      - 1   # std lower
      - 20  # sma
    - ema:
      - True
      - 12  # low
      - 26  # high
      - 50
strategy:
  rsi_lt:
    - True
    - 35  # lt: lower thab
  bbands: True
  ema_crossover: False
  ema_crossover: True
  flags_het: 3 # het: higher or equan than


